name: Docker

on:
  push:
  schedule:
    - cron: '0 3 * * 1'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  basic:
    name: Build and Push Basic Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Whats my IP
        run: curl --silent http://ipconfig.io

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build --file Dockerfile.basic --tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-basic:$(date +'%Y.%W')" --tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-basic:latest" .

      - name: Push to GitHub
        run: |
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-basic" --all-tags

  full:
    name: Build and Push Full Image
    runs-on: ubuntu-latest
    needs: basic

    steps:
      - uses: actions/checkout@v2

      - name: Whats my IP
        run: curl --silent http://ipconfig.io

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build --file Dockerfile.full --build-arg "VERSION=$(date +'%Y.%W')" --tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-full:$(date +'%Y.%W')" --tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-full:latest" .

      - name: Push to GitHub
        run: |
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-full" --all-tags
