name: Docker

on:
  push:
  schedule:
    - cron: '0 3 * * 1'

env:
  IMAGE_NAME: texlive-full

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Whats my IP
        run: curl --silent http://ipconfig.io

      - name: Build image
        run: docker build . --file Dockerfile --tag "${IMAGE_NAME}"

      - name: Log into GitHub registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin

      - name: Log into DockerHub registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Push image
        run: |
          VERSION=$(date +'%Y.%W')

          GITHUB_REGISTRY=$(echo "docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:${VERSION}" | tr '[:upper:]' '[:lower:]')
          DOCKERHUB_REGISTRY=$(echo "${{ secrets.DOCKERHUB_USER }}/${IMAGE_NAME}:${VERSION}" | tr '[:upper:]' '[:lower:]')

          docker tag "${IMAGE_NAME}" "${GITHUB_REGISTRY}"
          docker tag "${IMAGE_NAME}" "${DOCKERHUB_REGISTRY}"

          docker push "${GITHUB_REGISTRY}"
          docker push "${DOCKERHUB_REGISTRY}"

