name: Docker

on:
  push:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  basic:
    name: Build and Push Basic Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Whats my IP
        run: curl --silent http://ipconfig.io

      - name: Build image
        run: docker build . --file Dockerfile.basic --tag texlive-basic

      - name: Push to GitHub
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com --username "${{ github.actor }}" --password-stdin
          GITHUB_REGISTRY=$(echo "docker.pkg.github.com/${{ github.repository }}/texlive-basic:$(date +'%Y.%W')" | tr '[:upper:]' '[:lower:]')
          docker tag texlive-basic "${GITHUB_REGISTRY}"
          docker push "${GITHUB_REGISTRY}"

      - name: Push to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USER }}" --password-stdin
          DOCKERHUB_REGISTRY=$(echo "${{ secrets.DOCKERHUB_USER }}/texlive-basic:$(date +'%Y.%W')" | tr '[:upper:]' '[:lower:]')
          docker tag texlive-basic "${DOCKERHUB_REGISTRY}"
          docker push "${DOCKERHUB_REGISTRY}"

  full:
    name: Build and Push Full Image
    runs-on: ubuntu-latest
    needs: basic

    steps:
      - uses: actions/checkout@v2

      - name: Whats my IP
        run: curl --silent http://ipconfig.io

      - name: Build image
        run: docker build . --file Dockerfile.full --tag texlive-full --build-arg "VERSION=$(date +'%Y.%W')"

      - name: Push to GitHub
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com --username "${{ github.actor }}" --password-stdin
          GITHUB_REGISTRY=$(echo "docker.pkg.github.com/${{ github.repository }}/texlive-full:$(date +'%Y.%W')" | tr '[:upper:]' '[:lower:]')
          docker tag texlive-full "${GITHUB_REGISTRY}"
          docker push "${GITHUB_REGISTRY}"

      - name: Push to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USER }}" --password-stdin
          DOCKERHUB_REGISTRY=$(echo "${{ secrets.DOCKERHUB_USER }}/texlive-full:$(date +'%Y.%W')" | tr '[:upper:]' '[:lower:]')
          docker tag texlive-full "${DOCKERHUB_REGISTRY}"
          docker push "${DOCKERHUB_REGISTRY}"
