name: Docker

on:
  push:
  schedule:
    - cron: '0 3 * * 1'

env:
  IMAGE_NAME: texlive-full

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Whats my IP
        run: curl --silent http://ipconfig.io

      - name: Build image
        run: docker build . --file Dockerfile --tag "${IMAGE_NAME}"

      - name: Push to GitHub
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com --username "${{ github.actor }}" --password-stdin
          GITHUB_REGISTRY=$(echo "docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:$(date +'%Y.%W')" | tr '[:upper:]' '[:lower:]')
          docker tag "${IMAGE_NAME}" "${GITHUB_REGISTRY}"
          docker push "${GITHUB_REGISTRY}"

      - name: Push to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USER }}" --password-stdin
          DOCKERHUB_REGISTRY=$(echo "${{ secrets.DOCKERHUB_USER }}/${IMAGE_NAME}:$(date +'%Y.%W')" | tr '[:upper:]' '[:lower:]')
          docker tag "${IMAGE_NAME}" "${DOCKERHUB_REGISTRY}"
          docker push "${DOCKERHUB_REGISTRY}"
